version: '3'

services:
    jenkins:
        user: root
        image: "jenkins/jenkins:lts"
        ports:
         - "8082:8080"
         - "50000:50000"
        volumes:
         - /opt/docker/cicd/vol_jenkins:/var/jenkins_home
    nexus:
        image: "sonatype/nexus3"
        ports:
         - "8083:8081"
        volumes:
         - /opt/docker/cicd/vol_nexus:/nexus-data sonatype/nexus3
    gitlab:
        image: 'gitlab/gitlab-ee:latest'
        restart: always
        #hostname: 'gitlab.example.com'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab.example.com:8929'
                gitlab_rails['gitlab_shell_ssh_port'] = 2224
        ports:
         - '8929:8929'
         - '2224:22'
        volumes:
         - '/opt/docker/cicd/vol_gitlab/config:/etc/gitlab'
         - '/opt/docker/cicd/vol_gitlab/logs:/var/log/gitlab'
         - '/opt/docker/cicd/vol_gitlab/data:/var/opt/gitlab'
    sonar:
        image: 'sonarqube'
        ports:
         - '9000:9000'
         - '9092:9092'
